image: node:9-alpine

stages:
  - test
  - build
  - deploy

before_script:
  - apk --no-cache add gettext

variables:
  VERSION: 0.0.1


######################
# Tests
######################
package-tests:
  stage: test
  script:
    - envsubst '${VERSION}' < package.json > package.json.new
    - mv package.json.new package.json
    - npm install
    - npm run test


######################
# Build
######################
package-build:
  stage: build
  script:
    - envsubst '${VERSION}' < package.json > package.json.new
    - mv package.json.new package.json
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/*.js
    expire_in: 1 day
  only:
    - master
  except:
    - tags


######################
# Deploy
######################
package-deploy:
  stage: deploy
  script:
    - VERSION=$(echo ${CI_COMMIT_REF_NAME} | sed "s/v//")
    - export VERSION=$VERSION
    - envsubst '${VERSION}' < package.json > package.json.new
    - mv package.json.new package.json
    - npm install
    - npm run build
    - echo -e ${NPMRC} > ~/.npmrc
    - npm publish --access public
  only:
    - tags